aug:
  image_aug: true
  masked_language_model: true
backbone: vgg19_bn
cnn:
  hidden: 256
  ks:
  - - 2
    - 2
  - - 2
    - 2
  - - 2
    - 1
  - - 2
    - 1
  - - 1
    - 1
  pretrained: true
  ss:
  - - 2
    - 2
  - - 2
    - 2
  - - 2
    - 1
  - - 2
    - 1
  - - 1
    - 1
seq_modeling: transformer
transformer:
  d_model: 256
  dim_feedforward: 2048
  max_seq_length: 1024
  nhead: 8
  num_decoder_layers: 6
  num_encoder_layers: 6
  pos_dropout: 0.1
  trans_dropout: 0.1
  
dataloader:
  num_workers: 3
  pin_memory: true

device: cuda:0
optimizer:
  max_lr: 0.0003
  pct_start: 0.1
predictor:
  beamsearch: false


vocab: 'aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ0123456789!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~ '
weights: https://drive.google.com/file/d/1sLUUZpI0Q0M5xIruaD6T01cVx2RAWl2L/view?usp=sharing
